#pragma once

#define OCEAN_ROWS_MAX 20
#define OCEAN_COLUMNS_MAX 20
#define OCEAN_TILE_COUNT (OCEAN_ROWS_MAX * OCEAN_COLUMNS_MAX)

#define OCEAN_RADIUS 500

#define OCEAN_ALIGN_TO_MAP_ROWS 10
#define OCEAN_ALIGN_TO_MAP_COLUMNS 10