#pragma once

#define OCEAN_ROWS_MAX 100
#define OCEAN_COLUMNS_MAX 100
#define OCEAN_TILE_COUNT (OCEAN_ROWS_MAX * OCEAN_COLUMNS_MAX)

#define OCEAN_RADIUS 50.f

#define OCEAN_ALIGN_TO_MAP_ROWS 11
#define OCEAN_ALIGN_TO_MAP_COLUMNS 11