#pragma once

using GAME_OBJECT_TYPE = unsigned int;
enum GAME_OBJECT_TYPES
{
	/*
		Scenery
	*/

	GAME_OBJECT_TYPE_TILE,

	GAME_OBJECT_TYPE_SCENE_OBJECT,
	GAME_OBJECT_TYPE_BARREL,
	GAME_OBJECT_TYPE_BOX,
	GAME_OBJECT_TYPE_CACTUS,

	GAME_OBJECT_TYPE_CAGE,
	GAME_OBJECT_TYPE_COWSKULL,
	GAME_OBJECT_TYPE_FRUITTREE,

	GAME_OBJECT_TYPE_GIANTSKULL,
	GAME_OBJECT_TYPE_TOWER,
	GAME_OBJECT_TYPE_WINTERTREE,

	/*
		Living things
	*/

	GAME_OBJECT_TYPE_UNIT,

	/*
		Weapons
	*/

	GAME_OBJECT_TYPE_WEAPON_OFFSET_TAG,
	GAME_OBJECT_TYPE_WEAPON_SWORD,			// All weapons with meshes first

	GAME_OBJECT_TYPE_WEAPON_PROJECTILE,
	GAME_OBJECT_TYPE_WEAPON_FIST,

	/*
		Traps
	*/

	GAME_OBJECT_TYPE_TRAP_OFFSET_TAG,
	GAME_OBJECT_TYPE_TRAP_FIRE,
	GAME_OBJECT_TYPE_TRAP_FREEZE,
	GAME_OBJECT_TYPE_TRAP_SPRING,

	/*
		Powerups
	*/

	GAME_OBJECT_TYPE_POWERUP_OFFSET_TAG,
	GAME_OBJECT_TYPE_POWERUP_HEALTH_PACK,

	/*
		Misc
	*/

	GAME_OBJECT_TYPE_QUAD,
};

constexpr int OFFSET_TRAP = 3;

constexpr int MESH_TYPE_COUNT = 12;
constexpr int SCENE_OBJECT_TYPE_COUNT = 9;
constexpr int TRAP_TYPE_COUNT = 3; // Number of different trap types to be rendered
constexpr int WEAPON_TYPE_COUNT = 1; // Number of different weapon types to be rendered

constexpr int SCENE_OBJECT_ENUM_OFFSET = GAME_OBJECT_TYPE_SCENE_OBJECT + 1;